blank_issues_enabled: false
contact_links:
  - name: Questions about WOBC training
    url: https://github.com/JPichardo170A/Warrant-Officer-Basic-Course-Notes/issues
    about: For general questions about the training materials
